services:
  llm_guard_api:
    build:
      context: ..
      dockerfile: llm_guard_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config/scanners.yml:/home/user/app/config/scanners.yml
